default:
   app:
      port: 3000
      host: '0.0.0.0'
      logDir: 'logs'
      domain: 'localhost'
      authCookieName: 'auth'
      authCookieMaxAge: 3600 # 1 hour in seconds
   redis:
      host: '127.0.0.1'
      port: '6379'
   misc:
      oneDay: 86400000 # 1 day in milliseconds
      oneHour: 3600000 # 1 hour in milliseconds
      oneMinute: 60000 # 1 minute in milliseconds
test:
   app:
      port: 3000
      host: '0.0.0.0'
      logDir: 'logs'
production:
   app:
      port: 3000
      host: '0.0.0.0'
      logDir: 'logs'